import '@/styles/globals.css'

import { HeaderDashboard } from './components/header-dashboard'
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Painel do Usuário',
  description: 'Generated by create next app'
}

type RootLayoutProps = { children: React.ReactNode }

const user = {
  name: 'Pedro Galvão',
  email: 'pedro@gmail.com',
  imageUrl:
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80'
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <>
      <HeaderDashboard>{children}</HeaderDashboard>
      <Toaster />
    </>
  )
}

export default RootLayout
