import { Footer } from '@/components/interface/footer'
import { Header } from '@/components/interface/header'
import { Toaster } from '@/components/ui/toaster'

import { currentUser } from '@clerk/nextjs'

export const metadata = {
  title: 'Volitivo',
  description: 'Generated by create next app'
}

type RootLayoutProps = { children: React.ReactNode }

const RootLayout = async ({ children }: RootLayoutProps) => {
  const user = await currentUser()

  const infoUser = {
    userName: user?.username,
    image: user?.imageUrl
  }

  return (
    <>
      <Header user={infoUser} />
      <main>{children}</main>
      <Toaster />
      <Footer />
    </>
  )
}

export default RootLayout
