import { Footer } from '@/components/interface/footer'
import { Header } from '@/components/interface/header'
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Volitivo',
  description: 'Generated by create next app'
}

type RootLayoutProps = { children: React.ReactNode }

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <>
      <Header />
      <main>{children}</main>
      <Toaster />
      <Footer />
    </>
  )
}

export default RootLayout
